language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
# command to install dependencies
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libblas-dev liblapack-dev
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - echo "done" | python main.py examples/mechanism_synthesis.py
