language: python
python:
  # - "3.5"
  - "3.6"      # current default Python on Travis CI
  # - "3.7"
  - "3.8"
# command to install dependencies
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libopenblas-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install openblas; fi
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - echo "done" | python examples/mechanism_synthesis.py
